import pandas as pd


COLUMN_DESCRIPTIONS = {
    "Order_ID": "Unique identifier for a retail sales transaction.",
    "Order_Date": "Date when the sale occurred.",
    "Product_Category": "Category of the product sold.",
    "Total_Sales": "Sales amount or revenue generated by the transaction.",
    "Discount_Percent": "Discount applied to the transaction.",
    "Region": "Sales region associated with the transaction.",
    "Customer_Age": "Age of the customer.",
    "Customer_Gender": "Gender of the customer.",
    "Sales_Representative": "Sales representative responsible for the transaction."
}


SYNONYM_MAPPING = {
    "revenue": "Total_Sales",
    "sales": "Total_Sales",
    "sales amount": "Total_Sales",
    "total revenue": "Total_Sales",

    "category": "Product_Category",
    "product category": "Product_Category",

    "discount": "Discount_Percent",

    "region": "Region",
    "sales region": "Region",

    "date": "Order_Date",
    "sale date": "Order_Date",
    "sales date": "Order_Date",

    "age": "Customer_Age",
    "customer age": "Customer_Age",

    "gender": "Customer_Gender",
    "customer gender": "Customer_Gender",

    "representative": "Sales_Representative",
    "sales representative": "Sales_Representative"
}


def build_schema_context(df: pd.DataFrame):
    """
    Build compact dataset schema information for the LLM.
    """

    schema_lines = []

    for column in df.columns:

        dtype = str(df[column].dtype)

        samples = (
            df[column]
            .dropna()
            .astype(str)
            .unique()[:3]
            .tolist()
        )

        description = COLUMN_DESCRIPTIONS.get(
            column,
            "No description available."
        )

        schema_lines.append(
            f"- {column} | type={dtype} | "
            f"description={description} | "
            f"sample_values={samples}"
        )

    return "\n".join(schema_lines)


def build_system_prompt(df: pd.DataFrame):
    """
    Create a schema-aware system prompt.
    """

    schema_context = build_schema_context(df)

    synonym_text = "\n".join(
        [
            f"- {key} -> {value}"
            for key, value in SYNONYM_MAPPING.items()
        ]
    )

    return f"""
You are an AI data analytics assistant.

You are working with a retail sales dataset containing
100,000 sales transactions.

BUSINESS CONTEXT:
The dataset contains transaction IDs, product categories,
sales amounts, discounts, sales regions, transaction dates,
customer age, customer gender, and sales representatives.

DATASET SCHEMA:
{schema_context}

SYNONYM MAPPING:
{synonym_text}

RULES:
1. Use only columns listed in the dataset schema.
2. Never invent column names.
3. Treat revenue and sales as Total_Sales.
4. Treat category as Product_Category.
5. Treat region as Region.
6. Treat discount as Discount_Percent.
7. If the requested information is not available in the
   dataset, clearly state that.
8. Do not claim that Profit, Country, Customer Segment,
   Payment Method, Quantity, or Product Name exists.
9. Answer clearly and concisely.
"""


def build_code_generation_prompt(df, question):
    """
    Create a prompt asking the LLM to generate
    executable pandas code.
    """

    schema_context = build_schema_context(df)

    synonym_text = "\n".join(
        [
            f"- {key} -> {value}"
            for key, value in SYNONYM_MAPPING.items()
        ]
    )

    return f"""
You are a pandas data analyst.

Convert the user's natural-language question into
safe executable pandas code.

The DataFrame is named:

df

DATASET SCHEMA:
{schema_context}

SYNONYM MAPPING:
{synonym_text}

USER QUESTION:
{question}

STRICT RULES:

1. Use only pandas operations.
2. Use only columns listed in the schema.
3. Never invent columns.
4. Never import anything.
5. Never access files.
6. Never access the internet.
7. Never use os, sys, subprocess, requests,
   urllib, socket, open, eval, exec, or compile.
8. The dataframe already exists as df.
9. Store the final answer in a variable named result.
10. Prefer a pandas DataFrame as result.
11. Return ONLY Python code.
12. Do not use Markdown fences.
13. Keep code short and direct.
14. If returning multiple scalar values, use a one-row
    DataFrame with pd.DataFrame([{{...}}]).

Available analytical concepts include:
- Total sales/revenue
- Average sales
- Product category
- Sales region
- Customer age
- Customer gender
- Sales representative
- Discount
- Monthly/yearly sales trends

Example:

result = (
    df.groupby("Product_Category", as_index=False)["Total_Sales"]
    .sum()
    .sort_values("Total_Sales", ascending=False)
    .head(10)
)
"""


def build_result_explanation_prompt(
    question,
    result_text
):
    """
    Ask the LLM to explain an actual analytical result.
    """

    return f"""
You are an AI retail data analytics assistant.

The user asked:

{question}

The pandas query produced this REAL result:

{result_text}

Explain the result clearly.

Requirements:
- Base the answer only on the provided result.
- Do not invent values.
- Use Markdown formatting.
- Mention the most important finding.
- Keep the explanation concise.
"""